name: Move Task to Design Board

on:
  issues:
    types:
      - labeled
      - opened
      - edited

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event
        run: |
          echo "Issue labeled: ${{ github.event.label.name }}"